from setuptools import setup, find_packages

setup(
    name="community-notes-prediction",
    version="1.0.0",
    description="Predicting the effectiveness of crowd-sourced fact-checking using fine-tuned LLMs",
    author="Md Shahidul Salim, Rafa Pashkov, Mridul Madan",
    author_email="shahidul.salim@uml.edu",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "scikit-learn>=1.3.0",
        "torch>=2.1.0",
        "transformers>=4.37.0",
        "datasets>=2.14.0",
        "accelerate>=0.24.0",
        "tqdm>=4.65.0",
        "requests>=2.31.0",
        "aiohttp>=3.8.0",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "plotly>=5.17.0",
        "unsloth>=2024.6",
        "peft>=0.8.0",
        "bitsandbytes>=0.42.0",
        "trl>=0.7.0",
        "vllm>=0.5.0",
        "pyyaml>=6.0",
        "pydantic>=2.0.0",
        "fastapi>=0.104.0",
        "uvicorn>=0.24.0",
    ],
    python_requires=">=3.10",
)
